//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMIT.Framework.DAL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMIT.Framework.DAL.Properties.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrada a chave [DatabaseDefault] no AppSettings. Esta configuração é obrigatória para o funcionamento do framework..
        /// </summary>
        internal static string Erro_AppSettings_DatabaseDefault {
            get {
                return ResourceManager.GetString("Erro_AppSettings_DatabaseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrada a chave [SchemaDefault] no AppSettings. Esta configuração é obrigatória para o funcionamento do framework..
        /// </summary>
        internal static string Erro_AppSettings_SchemaDefault {
            get {
                return ResourceManager.GetString("Erro_AppSettings_SchemaDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrada a chave [SqlServerVersion] no AppSettings. Esta configuração é obrigatória para o funcionamento do framework..
        /// </summary>
        internal static string Erro_AppSettings_SqlServerVersion {
            get {
                return ResourceManager.GetString("Erro_AppSettings_SqlServerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível recuperar a connection string..
        /// </summary>
        internal static string Erro_ConnectionString {
            get {
                return ResourceManager.GetString("Erro_ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível recuperar a connection string apartir do indice informado..
        /// </summary>
        internal static string Erro_ConnectionString_Index {
            get {
                return ResourceManager.GetString("Erro_ConnectionString_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível recuperar a connection string apartir do identificador informado..
        /// </summary>
        internal static string Erro_ConnectionString_Name {
            get {
                return ResourceManager.GetString("Erro_ConnectionString_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um erro inexperado na camada DAL.
        /// </summary>
        internal static string Erro_Geral {
            get {
                return ResourceManager.GetString("Erro_Geral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House um erro ao estabelecer uma conexão com o banco de dados.
        /// </summary>
        internal static string Erro_Geral_Conexao {
            get {
                return ResourceManager.GetString("Erro_Geral_Conexao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível gerar o Log:.
        /// </summary>
        internal static string Erro_Geral_Log {
            get {
                return ResourceManager.GetString("Erro_Geral_Log", resourceCulture);
            }
        }
    }
}
